[INFO main 32] Initialising Python Geth Console...
[INFO main 38] Initialising peer buffer...
[INFO main 38] Initialising TCP server...
[INFO main 38] Initialising RandB board...
[INFO main 38] Initialising ground-sensors...
[INFO main 39] Initialising random-walk...
[INFO main 5381] Starting Experiment
[INFO main 11572] Added peer: 2, enode: enode://dad2cb74f9b1c591cdc92fec9a8c0835eb06e2ce882ff4451d22a2853719ddc76f6bc30d66e48c2af901b944c41f04b451bb7ea21c86c9c974249c09f705eb69@10.0.1.4:30303?discport=0
[DEBUG events 13570] 0x0000000000000000000000000000000000000000
[DEBUG events 13575] Registered on-chain
[WARNING events 16552] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 17549] Removed peer: 2
[DEBUG events 23556] 0x0fa9077350FC3Ee6924743e1AD9b735c657C455E
[DEBUG events 23558] Registered on-chain
[INFO main 27551] Added peer: 8, enode: enode://15a055abaa2dc70996901114bbf5cf0bfb131aacc74bad6e9a929a248509cfeba97577f7b5292e42a18ea918abb19d8adbf4166420e15047926d3fbc125bf6e6@10.0.1.10:30303?discport=0
[DEBUG events 37497] Asked for UBI: 40
