[INFO main 29] Initialising Python Geth Console...
[INFO main 36] Initialising peer buffer...
[INFO main 36] Initialising TCP server...
[INFO main 36] Initialising RandB board...
[INFO main 36] Initialising ground-sensors...
[INFO main 36] Initialising random-walk...
[INFO main 5247] Starting Experiment
[INFO main 6284] Added peer: 8, enode: enode://15a055abaa2dc70996901114bbf5cf0bfb131aacc74bad6e9a929a248509cfeba97577f7b5292e42a18ea918abb19d8adbf4166420e15047926d3fbc125bf6e6@10.0.1.10:30303?discport=0
[INFO main 9363] Added peer: 3, enode: enode://cb6ef100ffa12fca6c0651dce5537c88be53f8a17f6fa69b895a82b20f5e196d56cd32c619abf29dbe94be271a61b964ea492bc3bbab6b6c124d69e11f8f41d7@10.0.1.5:30303?discport=0
[INFO main 11390] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[DEBUG events 15364] 0x0000000000000000000000000000000000000000
[DEBUG events 15365] Registered on-chain
[WARNING events 18372] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 22363] Removed peer: 8
[INFO main 22377] Removed peer: 3
[INFO main 25369] Removed peer: 6
[DEBUG events 32384] 0x633462025cF12D347C0dF50B2114E65aa364f0a6
[DEBUG events 32386] Registered on-chain
[DEBUG events 37377] Asked for UBI: 40
