[INFO main 26] Initialising Python Geth Console...
[INFO main 32] Initialising peer buffer...
[INFO main 32] Initialising TCP server...
[INFO main 32] Initialising RandB board...
[INFO main 32] Initialising ground-sensors...
[INFO main 32] Initialising random-walk...
[INFO main 5102] Starting Experiment
[DEBUG events 15190] 0x0000000000000000000000000000000000000000
[DEBUG events 15191] Registered on-chain
[WARNING events 18175] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 20200] Added peer: 5, enode: enode://20602804a9d04256a808da435526817cd62fa68bcfcd4ca0798c496c06f3165dfe1b659316328cdaa3f10b10be8aecf69d8663d093b4c9dcd9e380f8064ec560@10.0.1.7:30303?discport=0
[INFO main 24186] Removed peer: 5
[DEBUG events 28202] 0x0000000000000000000000000000000000000000
[DEBUG events 28203] Registered on-chain
[WARNING events 31178] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 31192] Added peer: 5, enode: enode://20602804a9d04256a808da435526817cd62fa68bcfcd4ca0798c496c06f3165dfe1b659316328cdaa3f10b10be8aecf69d8663d093b4c9dcd9e380f8064ec560@10.0.1.7:30303?discport=0
[DEBUG events 37160] 0xc72B1b70e69D270544369132d53529e37Be87742
[DEBUG events 37160] Registered on-chain
[DEBUG events 37343] Asked for UBI: 40
