[INFO main 26] Initialising Python Geth Console...
[INFO main 33] Initialising peer buffer...
[INFO main 33] Initialising TCP server...
[INFO main 33] Initialising RandB board...
[INFO main 33] Initialising ground-sensors...
[INFO main 33] Initialising random-walk...
[INFO main 5197] Starting Experiment
[INFO main 9290] Added peer: 2, enode: enode://dad2cb74f9b1c591cdc92fec9a8c0835eb06e2ce882ff4451d22a2853719ddc76f6bc30d66e48c2af901b944c41f04b451bb7ea21c86c9c974249c09f705eb69@10.0.1.4:30303?discport=0
[INFO main 10316] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[DEBUG events 15302] 0x0000000000000000000000000000000000000000
[DEBUG events 15303] Registered on-chain
[WARNING events 18296] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 20321] Added peer: 7, enode: enode://ebfd2f831931058cbd539741cb07eb384ef9073668adb146ace42a0dd71d5746fbc564283c828df0f97d8dad1f12da1efb60929261214209eb7864bd64913508@10.0.1.9:30303?discport=0
[INFO main 21299] Removed peer: 2
[INFO main 22311] Removed peer: 6
[DEBUG events 25296] 0x036D6B4DA0b4Eeb9d312E958c2937D9016765F50
[DEBUG events 25304] Registered on-chain
[INFO main 31298] Added peer: 2, enode: enode://dad2cb74f9b1c591cdc92fec9a8c0835eb06e2ce882ff4451d22a2853719ddc76f6bc30d66e48c2af901b944c41f04b451bb7ea21c86c9c974249c09f705eb69@10.0.1.4:30303?discport=0
[INFO main 32306] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[DEBUG events 37313] Asked for UBI: 40
