[INFO main 26] Initialising Python Geth Console...
[INFO main 32] Initialising peer buffer...
[INFO main 32] Initialising TCP server...
[INFO main 32] Initialising RandB board...
[INFO main 32] Initialising ground-sensors...
[INFO main 32] Initialising random-walk...
[INFO main 5350] Starting Experiment
[INFO main 8497] Added peer: 5, enode: enode://20602804a9d04256a808da435526817cd62fa68bcfcd4ca0798c496c06f3165dfe1b659316328cdaa3f10b10be8aecf69d8663d093b4c9dcd9e380f8064ec560@10.0.1.7:30303?discport=0
[INFO main 13485] Added peer: 1, enode: enode://6bb18517035c4ad2668fbcb450a1dd84af49270dc8c395208e4fe979bc97a90338cae69cce9e3502e4c116a258c1a2a6d56ff61915269bb7fd079b56440556a3@10.0.1.3:30303?discport=0
[DEBUG events 15494] 0x0000000000000000000000000000000000000000
[DEBUG events 15494] Registered on-chain
[INFO main 15495] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[WARNING events 17487] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 20490] Removed peer: 1
[INFO main 20518] Removed peer: 5
[DEBUG events 23503] 0xA4b1B07974bF67f04EC51bEcABF4aD62106B1Dd0
[DEBUG events 23504] Registered on-chain
[INFO main 29490] Added peer: 8, enode: enode://15a055abaa2dc70996901114bbf5cf0bfb131aacc74bad6e9a929a248509cfeba97577f7b5292e42a18ea918abb19d8adbf4166420e15047926d3fbc125bf6e6@10.0.1.10:30303?discport=0
[INFO main 30488] Added peer: 5, enode: enode://20602804a9d04256a808da435526817cd62fa68bcfcd4ca0798c496c06f3165dfe1b659316328cdaa3f10b10be8aecf69d8663d093b4c9dcd9e380f8064ec560@10.0.1.7:30303?discport=0
[DEBUG events 37460] Asked for UBI: 40
